# Generated by Django 4.1.4 on 2022-12-11 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categorie de formation",
                "verbose_name_plural": "Categorie de formation",
            },
        ),
        migrations.CreateModel(
            name="VideoFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                (
                    "video",
                    models.FileField(
                        upload_to="videos-formations", verbose_name="Video"
                    ),
                ),
                ("prix", models.PositiveIntegerField(verbose_name="Prix")),
                ("description", models.TextField(blank=True)),
                (
                    "downloadNumber",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Nombre de téléchargements",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(upload_to="videos", verbose_name="Poster"),
                ),
                (
                    "note",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        editable=False,
                        max_digits=2,
                        verbose_name="Note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "access_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="video_formations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="api.categorieformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video de formation",
                "verbose_name_plural": "Videos de formation",
            },
        ),
        migrations.CreateModel(
            name="PaymentVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=255)),
                ("transaction_id", models.CharField(max_length=255)),
                (
                    "transaction_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date et heure de la transaction",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(blank=True, null=True, verbose_name="montant"),
                ),
                ("devise", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_prefix",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.videoformation",
                    ),
                ),
            ],
        ),
    ]
