# Generated by Django 4.1.4 on 2022-12-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvideo",
            name="transaction_date",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="Date et heure de la transaction",
            ),
        ),
    ]
